{% set version = "1.1" %}

package:
  name: py-rouge
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/py-rouge/py-rouge-{{ version }}.tar.gz
  sha256: b6caf2f031c45f699a9481c8962b8c33688165a3f2a22e1bfbaede8e073d6bb0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    # - bsddb3
    - nltk
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - rouge
  # # tests aren't packaged, and github has no tags to pull from, see Diego999/py-rouge#16
  # source_files:
  #  - tests/
  # commands:
  #   - python -m unittest tests

about:
  home: https://github.com/Diego999/py-rouge
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Full Python implementation of the ROUGE metric, producing same results as in the official perl implementation."
  dev_url: https://github.com/Diego999/py-rouge

extra:
  recipe-maintainers:
    - h-vetinari
